services:
  db:
    container_name: nedon-db
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: nedon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9876:5432"
    expose:
      - "9876"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
